# Generated by Django 4.0.4 on 2022-05-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0004_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
