# Generated by Django 4.0.4 on 2022-05-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0005_student_password_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='permanent_address',
        ),
    ]
