# Generated by Django 4.0.4 on 2022-05-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0006_rename_address_student_permanent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=110),
        ),
    ]
