# Generated by Django 4.0.4 on 2022-06-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0010_rename_address_staff_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='addres',
            new_name='permanent_address',
        ),
    ]
