# Generated by Django 4.0.4 on 2022-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0013_staff_permanent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='permanent_address',
            field=models.TextField(verbose_name=100),
        ),
    ]
