# Generated by Django 4.0.4 on 2022-06-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0014_alter_staff_permanent_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='permanent_address',
            new_name='address',
        ),
    ]
