# Generated by Django 4.0.4 on 2022-06-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0015_rename_permanent_address_staff_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
