# Generated by Django 4.0.4 on 2022-06-09 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0016_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Student_app.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student_app.staff'),
            preserve_default=False,
        ),
    ]
