# Generated by Django 4.0.4 on 2022-06-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0017_subjects_course_subjects_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='update_at',
        ),
    ]
