# Generated by Django 4.0.4 on 2022-06-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0018_remove_subjects_create_at_remove_subjects_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_year',
            name='session_end',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='session_year',
            name='session_start',
            field=models.CharField(max_length=1000),
        ),
    ]
